// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUU1g4k84qUMl7fZsKa8wB_3K0OgQWrPY',
    appId: '1:1029365395735:android:a572228c56d36090104752',
    messagingSenderId: '1029365395735',
    projectId: 'authproject-6f0da',
    storageBucket: 'authproject-6f0da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4TkSRZ2nJqhTbKJf-nMjd3CobP_krxdg',
    appId: '1:1029365395735:ios:2ca3a1eec45b4ef4104752',
    messagingSenderId: '1029365395735',
    projectId: 'authproject-6f0da',
    storageBucket: 'authproject-6f0da.firebasestorage.app',
    androidClientId: '1029365395735-sidr62qhd1idsafkmm3k8q8bld2nn7on.apps.googleusercontent.com',
    iosClientId: '1029365395735-k83udo39m88f6pbma611li5912d00ef3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourexplorer',
  );
}
